/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const IconLocalLogo: typeof import('~icons/local/logo.jsx')['default']
  const IconLocalQq: typeof import('~icons/local/qq.jsx')['default']
}
